### ISSUE TITLE
Android and iOS build is not working

### ISSUE THREAD

**Issue by soemo** [trigger-corp/forge#101]
Hello @antoinevg 

currently we are facing this error during a build with forge version 2.9.5
>  ('Connection aborted.', BadStatusLine('No status line received - the server has closed the connection',))

Can you please check it?

````
######## build android

2021-09-21 14:05:48,583 [  DEBUG] Forge build tools version: 3.5.9
2021-09-21 14:05:48,583 [  DEBUG] main: {"server": "https://trigger.io/api/"}
2021-09-21 14:05:48,583 [  DEBUG] port: 38394
2021-09-21 14:05:48,591 [  DEBUG] GET https://trigger.io/api/v1/version_check/3/5/9/
2021-09-21 14:05:48,762 [  DEBUG] Starting new HTTPS connection (1): trigger.io:443
2021-09-21 14:05:48,990 [  ERROR] Something went wrong that we didn't expect:
2021-09-21 14:05:48,990 [  ERROR] ('Connection aborted.', BadStatusLine('No status line received - the server has closed the connection',))
2021-09-21 14:05:48,990 [  DEBUG] Traceback (most recent call last):
  File "/Applications/TriggerToolkit.app/Contents/MacOS/build-tools/forge/async.py", line 106, in run
    result = self._target(*self._args, **self._kwargs)
  File "/Applications/TriggerToolkit.app/Contents/MacOS/build-tools/forge/main.py", line 346, in development_build
    updater.distribution_aware_updater().check_version(remote)
  File "/Applications/TriggerToolkit.app/Contents/MacOS/build-tools/forge/updater.py", line 132, in check_version
    return self.force_check_version(remote)
  File "/Applications/TriggerToolkit.app/Contents/MacOS/build-tools/forge/updater.py", line 115, in force_check_version
    'version_check/{version}/'.format(version=forge.get_version().replace('.', '/'))
  File "/Applications/TriggerToolkit.app/Contents/MacOS/build-tools/forge/remote.py", line 488, in _api_get
    resp = self.__get_or_post(absolute_url, *args, **kw)
  File "/Applications/TriggerToolkit.app/Contents/MacOS/build-tools/forge/remote.py", line 411, in __get_or_post
    resp = getattr(self.session, method.lower())(url, *args, **kw)
  File "/Applications/TriggerToolkit.app/Contents/MacOS/build-tools/forge-dependencies/requests/sessions.py", line 543, in get
    return self.request('GET', url, **kwargs)
  File "/Applications/TriggerToolkit.app/Contents/MacOS/build-tools/forge-dependencies/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/Applications/TriggerToolkit.app/Contents/MacOS/build-tools/forge-dependencies/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/Applications/TriggerToolkit.app/Contents/MacOS/build-tools/forge-dependencies/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', BadStatusLine('No status line received - the server has closed the connection',))
````

**Comment by antoinevg** [comment]
My apologies, I've needed to do some emergency server maintenance since this morning. 

This has meant things have been a bit up & down - can you please check again now?

**Comment by soemo** [comment]
Thanks it is working again
