### ISSUE TITLE
"npm install @triggercorp/forge" fails on Fedora 32

### ISSUE THREAD

**Issue by antoinevg** [trigger-corp/forge#83]
**To Reproduce**
1. Install Fedora 32, nodejs, npm
2. Run: `npm install @triggercorp/forge`

**Expected behaviour**
An error-free installation of forge

**Actual behaviour**

    > @triggercorp/forge@3.5.8 postinstall /home/antoine/deleteme/node_modules/@triggercorp/forge
    > node scripts/postinstall.js

    postinstall:info verifying installation
    postinstall:error error verifying installation, exited with code: 1
    postinstall:info
    postinstall:error Traceback (most recent call last):
    postinstall:error   File "/home/antoine/deleteme/node_modules/.bin/forge", line 20, in <module>
    postinstall:error     forge = __import__("forge.main")
    postinstall:error   File "/home/antoine/deleteme/node_modules/@triggercorp/forge/bin/native/build-tools/forge/__init__.py", line 18
    postinstall:error     from forge import async
    postinstall:error                       ^
    postinstall:error SyntaxError: invalid syntax
    postinstall:error
    npm WARN deleteme@1.0.0 No description
    npm WARN deleteme@1.0.0 No repository field.

    npm ERR! code ELIFECYCLE
    npm ERR! errno 1
    npm ERR! @triggercorp/forge@3.5.8 postinstall: `node scripts/postinstall.js`
    npm ERR! Exit status 1
    npm ERR!
    npm ERR! Failed at the @triggercorp/forge@3.5.8 postinstall script.
    npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

    npm ERR! A complete log of this run can be found in:
    npm ERR!     /home/antoine/.npm/_logs/2020-10-02T12_20_31_244Z-debug.log

**Comment by antoinevg** [comment]
It looks like the issue is caused by Fedora using Python 3 as the default system python.

In the long run the solution is to continue with the process of migrating to Python 3.

Until then, a horrible workaround is to either install [pyenv](https://github.com/pyenv/pyenv) or do something like:

```
sudo dnf install python27
mkdir py2
ln -s /usr/bin/python2 py2/python
PATH=$(pwd)/py2:$PATH
npm install @triggercorp/forge    
```
